'use strict';

/**
 * @typedef {Object} FormCodegenItem
 * @property {import('../crawler/formScanner').ScannedForm} form
 * @property {any[]} cases
 * @property {any[]} expectations
 */

/**
 * Converts form-fill test cases plus visited-page snapshots into a single
 * Playwright TypeScript spec file (login helper, per-field-type fill logic,
 * screenshot-based golden-master assertions).
 * @param {FormCodegenItem[]} items
 * @param {{login?: any, visitedUrls?: string[], visitedPages?: any[]}} [options]
 */
function generatePlaywrightCode(items, options = {}) {
  const visited = Array.from(new Set(options.visitedUrls ?? []));
  const firstUrl = items[0]?.form.url ?? visited[0] ?? 'http://localhost';
  const totalFormCases = items.reduce((n, i) => n + i.cases.length, 0);

  const header = `// Auto-generated by Web Security Hub Test Generator
// forms: ${items.length} / total form cases: ${totalFormCases}
// visited pages: ${visited.length}
//
// BASE_URL can be overridden via the BASE_URL env var (e.g. old vs new server comparison).
import { test, expect } from 'playwright/test';

const BASE_URL = process.env.BASE_URL ?? ${JSON.stringify(originOf(firstUrl))};
const STRICT_PAGE_ASSERT = /^(1|true|yes)$/i.test(process.env.GOLDEN_MASTER_STRICT_PAGE_ASSERT ?? '');
const DEEP_INTERACTIVE_FLOW = /^(1|true|yes)$/i.test(process.env.GOLDEN_MASTER_DEEP_INTERACTIVE_FLOW ?? '');
const BASIC_USER = process.env.GOLDEN_MASTER_BASIC_USER ?? process.env.GM_BASIC_USER ?? '';
const BASIC_PASS = process.env.GOLDEN_MASTER_BASIC_PASS ?? process.env.GM_BASIC_PASS ?? '';
const WEB_SECURITY_PROXY_URL = process.env.WEB_SECURITY_PROXY_URL ?? '';
if (BASIC_USER) {
  test.use({ httpCredentials: { username: BASIC_USER, password: BASIC_PASS } });
}
if (WEB_SECURITY_PROXY_URL) {
  test.use({ proxy: { server: WEB_SECURITY_PROXY_URL } });
}
${renderLoginHelper(options.login)}
${renderFormReadyHelper()}`;

  const formBlocks = items.map((item, idx) => renderForm(item, idx)).filter(Boolean).join('\n\n');
  const pageBlock = renderVisitedPages(options.visitedPages ?? [], visited);

  return header + '\n' + [formBlocks, pageBlock].filter(Boolean).join('\n\n') + '\n';
}

function renderForm(item, idx) {
  if (!item.cases.length) return '';

  const { form } = item;
  const errorMessages = item.expectations.filter((e) => e.kind === 'error' && e.messageContains).map((e) => e.messageContains);

  const desc = `form#${idx + 1} ${pathOf(form.url)}`;
  const body = item.cases.map((tc) => renderCase(form, tc, errorMessages)).join('\n');
  return `test.describe(${JSON.stringify(desc)}, () => {\n${body}\n});`;
}

function renderCase(form, tc, errorMessages) {
  const lines = [];
  const handledRadioGroups = new Set();
  lines.push(`  test(${JSON.stringify(tc.name + ' / ' + tc.id)}, async ({ page }) => {`);
  lines.push(`    await page.setExtraHTTPHeaders({ 'X-Web-Security-Case-Id': ${JSON.stringify(tc.id)} });`);
  const normalizedSelectors = Object.keys(tc.assignments).map(normalizeSelectorForPlayback);
  const normalizedSubmitSelector = normalizeSelectorForPlayback(form.submitSelector ?? '');
  lines.push(`    await gotoWithOptionalLogin(page, ${JSON.stringify(pathOf(form.url))});`);
  if (form.preSteps?.length) {
    lines.push(`    await runPreSteps(page, ${JSON.stringify(form.preSteps)});`);
  }
  lines.push(`    await ensureFormReadyForAssignments(page, ${JSON.stringify(normalizedSelectors)}, ${JSON.stringify(normalizedSubmitSelector)});`);

  for (const [selector, gv] of Object.entries(tc.assignments)) {
    const field = form.fields.find((f) => f.selector === selector);
    if (!field) continue;

    const sel = JSON.stringify(normalizeSelectorForPlayback(selector));
    if (field.tag === 'select') {
      if (gv.value === '__not_in_options__') {
        lines.push(`    // ${gv.kind}: ${gv.rationale} (value not in options; skipping the select action itself)`);
      } else {
        lines.push(`    await page.selectOption(${sel}, ${JSON.stringify(gv.value)}, { timeout: 5000 }); // ${gv.kind}: ${gv.rationale}`);
      }
    } else if (field.type === 'checkbox') {
      lines.push(gv.value === 'on' ? `    await page.check(${sel}); // ${gv.kind}` : `    await page.uncheck(${sel}); // ${gv.kind}`);
    } else if (field.type === 'radio') {
      const radioGroupKey = field.name || selector;
      if (handledRadioGroups.has(radioGroupKey)) continue;
      handledRadioGroups.add(radioGroupKey);
      if (!gv.value || gv.value === 'off' || gv.value === '__not_in_options__') {
        lines.push(`    await clearRadioGroupSelection(page, ${sel}); // ${gv.kind}: ${gv.rationale}`);
      } else {
        lines.push(`    await selectRadioValue(page, ${sel}, ${JSON.stringify(gv.value)}); // ${gv.kind}: ${gv.rationale}`);
      }
    } else {
      lines.push(`    await page.fill(${sel}, ${JSON.stringify(gv.value)}, { timeout: 5000 }); // ${gv.kind}: ${gv.rationale}`);
    }
  }

  if (form.submitSelector) {
    lines.push(`    await Promise.all([`);
    lines.push(`      page.waitForNavigation({ timeout: 12000 }).catch(() => {}),`);
    lines.push(`      page.click(${JSON.stringify(normalizedSubmitSelector)}),`);
    lines.push(`    ]);`);
    lines.push(`    await page.waitForLoadState('networkidle', { timeout: 5000 }).catch(() => {});`);
  }

  const isAbnormal = Object.values(tc.assignments).some((v) => v.kind === 'abnormal');
  if (isAbnormal && errorMessages.length) {
    lines.push(`    // Rule Spec expectation (at least one of these error strings should appear)`);
    const ors = errorMessages.map((m) => `(await page.locator('body').textContent() ?? '').includes(${JSON.stringify(m)})`).join(' ||\n      ');
    lines.push(`    expect(\n      ${ors}\n    ).toBeTruthy();`);
  }

  lines.push(`    // --- golden master ---`);
  lines.push(`    await expect(page).toHaveScreenshot(${JSON.stringify(tc.id + '.png')}, { fullPage: true });`);
  lines.push(`  });`);
  return lines.join('\n');
}

function normalizeSelectorForPlayback(selector) {
  if (!selector) return selector;
  if (!selector.startsWith('#')) return selector;
  const id = selector.slice(1);
  if (!/[\[\]]/.test(id)) return selector;
  const escaped = id.replace(/["\\]/g, '\\$&');
  return `[id="${escaped}"]`;
}

function renderVisitedPages(snapshots, fallbackUrls) {
  const source = snapshots.length ? snapshots : fallbackUrls.map((u) => ({ url: u, title: '', markers: [], textHash: '' }));
  if (!source.length) return '';

  const byPath = new Map();
  for (const s of source) {
    const p = pathOf(s.url);
    if (!p || byPath.has(p)) continue;
    byPath.set(p, s);
  }
  if (!byPath.size) return '';

  const lines = [];
  lines.push(`test.describe('page regression (crawl results)', () => {`);
  Array.from(byPath.entries()).forEach(([p, snapshot], idx) => {
    const id = String(idx + 1).padStart(3, '0');
    const slug = `page-${id}-${slugifyPath(p)}`;
    lines.push(`  test(${JSON.stringify(`page #${id} ${p}`)}, async ({ page }) => {`);
    lines.push(`    await gotoWithOptionalLogin(page, ${JSON.stringify(p)});`);
    lines.push(`    await page.waitForLoadState('networkidle').catch(() => {});`);
    lines.push(`    await expect(page).toHaveScreenshot(${JSON.stringify(`${slug}.png`)}, { fullPage: true });`);
    if (snapshot.title) {
      lines.push(`    if (STRICT_PAGE_ASSERT) expect(await page.title()).toContain(${JSON.stringify(snapshot.title.slice(0, 40))});`);
    }
    if (snapshot.markers.length) {
      lines.push(`    {`);
      lines.push(`      const text = normalizeGoldenText(await page.locator('body').innerText().catch(() => ''));`);
      lines.push(`      const markers = ${JSON.stringify(snapshot.markers)};`);
      lines.push(`      if (STRICT_PAGE_ASSERT) expect(markers.some((m) => text.includes(m))).toBeTruthy();`);
      lines.push(`    }`);
    }
    if (snapshot.textHash) {
      lines.push(`    {`);
      lines.push(`      const text = normalizeGoldenText(await page.locator('body').innerText().catch(() => ''));`);
      lines.push(`      const title = await page.title().catch(() => '');`);
      lines.push(`      if (STRICT_PAGE_ASSERT) expect(hashForGoldenMaster(title + '\\n' + text)).toBe(${JSON.stringify(snapshot.textHash)});`);
      lines.push(`    }`);
    }
    lines.push(`  });`);

    lines.push(`  if (DEEP_INTERACTIVE_FLOW) {`);
    lines.push(`    test(${JSON.stringify(`page #${id} ${p} / button exploration`)}, async ({ page }) => {`);
    lines.push(`      await exploreInteractiveFlow(page, ${JSON.stringify(p)}, ${JSON.stringify(slug)});`);
    lines.push(`    });`);
    lines.push(`  }`);
  });
  lines.push(`});`);
  lines.push(``);
  lines.push(`async function exploreInteractiveFlow(page, path, prefix) {`);
  lines.push(`  await gotoWithOptionalLogin(page, path);`);
  lines.push(`  const firstActions = await collectSafeClickTargets(page);`);
  lines.push(`  for (let i = 0; i < Math.min(firstActions.length, 3); i++) {`);
  lines.push(`    const a1 = firstActions[i];`);
  lines.push(`    await gotoWithOptionalLogin(page, path);`);
  lines.push(`    if (!(await tryClickSelector(page, a1.selector))) continue;`);
  lines.push(`    await page.waitForLoadState('networkidle').catch(() => {});`);
  lines.push(`    await expect(page).toHaveScreenshot(prefix + '-action1-' + String(i + 1).padStart(2, '0') + '.png', { fullPage: true });`);
  lines.push(``);
  lines.push(`    const secondActions = await collectSafeClickTargets(page);`);
  lines.push(`    for (let j = 0; j < Math.min(secondActions.length, 2); j++) {`);
  lines.push(`      const a2 = secondActions[j];`);
  lines.push(`      await gotoWithOptionalLogin(page, path);`);
  lines.push(`      if (!(await tryClickSelector(page, a1.selector))) continue;`);
  lines.push(`      await page.waitForLoadState('networkidle').catch(() => {});`);
  lines.push(`      if (!(await tryClickSelector(page, a2.selector))) continue;`);
  lines.push(`      await page.waitForLoadState('networkidle').catch(() => {});`);
  lines.push(`      await expect(page).toHaveScreenshot(prefix + '-action1-' + String(i + 1).padStart(2, '0') + '-action2-' + String(j + 1).padStart(2, '0') + '.png', { fullPage: true });`);
  lines.push(`    }`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`async function collectSafeClickTargets(page) {`);
  lines.push(`  const selectors = await page.evaluate(() => {`);
  lines.push(`    function cssEscape(s) { return s.replace(/["\\\\]/g, '\\\\$&'); }`);
  lines.push(`    function stableSelector(el) {`);
  lines.push(`      if (el.id) return '#' + cssEscape(el.id);`);
  lines.push(`      const name = el.getAttribute('name');`);
  lines.push(`      const tag = el.tagName.toLowerCase();`);
  lines.push(`      if (name) return tag + '[name="' + cssEscape(name) + '"]';`);
  lines.push(`      const parts = [];`);
  lines.push(`      let cur = el;`);
  lines.push(`      while (cur && cur.tagName.toLowerCase() !== 'html') {`);
  lines.push(`        const parent = cur.parentElement;`);
  lines.push(`        const t = cur.tagName.toLowerCase();`);
  lines.push(`        if (!parent) { parts.unshift(t); break; }`);
  lines.push(`        const same = Array.from(parent.children).filter((c) => c.tagName === cur.tagName);`);
  lines.push(`        const idx = same.indexOf(cur) + 1;`);
  lines.push(`        parts.unshift(t + ':nth-of-type(' + idx + ')');`);
  lines.push(`        cur = parent;`);
  lines.push(`      }`);
  lines.push(`      return parts.join(' > ');`);
  lines.push(`    }`);
  lines.push(`    const nodes = Array.from(document.querySelectorAll('main button, main [role="button"], main input[type="submit"], main input[type="button"], main a[role="button"], main a[href], button, [role="button"], input[type="submit"], input[type="button"], a[role="button"], a[href]'));`);
  lines.push(`    const out = [];`);
  lines.push(`    for (const el of nodes) {`);
  lines.push(`      if (el.closest('header, nav, footer')) continue;`);
  lines.push(`      const style = getComputedStyle(el);`);
  lines.push(`      const rect = el.getBoundingClientRect();`);
  lines.push(`      if (style.display === 'none' || style.visibility === 'hidden' || rect.width <= 0 || rect.height <= 0) continue;`);
  lines.push(`      const text = ((el.textContent || '') + ' ' + (el.value || '')).trim();`);
  lines.push(`      if (/(削除|退会|解約|キャンセル|停止|ログアウト|logout|destroy|delete)/i.test(text)) continue;`);
  lines.push(`      out.push({ selector: stableSelector(el), text: text.slice(0, 60) });`);
  lines.push(`      if (out.length >= 8) break;`);
  lines.push(`    }`);
  lines.push(`    return out;`);
  lines.push(`  });`);
  lines.push(`  return selectors;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`async function tryClickSelector(page, selector) {`);
  lines.push(`  try {`);
  lines.push(`    const target = page.locator(selector).first();`);
  lines.push(`    if (!(await target.count().catch(() => 0))) return false;`);
  lines.push(`    await target.click({ timeout: 3000 }).catch(async () => {`);
  lines.push(`      await target.scrollIntoViewIfNeeded().catch(() => {});`);
  lines.push(`      await target.click({ force: true, timeout: 3000 }).catch(() => {});`);
  lines.push(`    });`);
  lines.push(`    return true;`);
  lines.push(`  } catch {`);
  lines.push(`    return false;`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`function normalizeGoldenText(s) {`);
  lines.push(`  return (s || '').replace(/\\s+/g, ' ').trim();`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`function hashForGoldenMaster(s) {`);
  lines.push(`  let h = 2166136261;`);
  lines.push(`  for (let i = 0; i < s.length; i++) {`);
  lines.push(`    h ^= s.charCodeAt(i);`);
  lines.push(`    h = Math.imul(h, 16777619);`);
  lines.push(`  }`);
  lines.push(`  return (h >>> 0).toString(16).padStart(8, '0');`);
  lines.push(`}`);
  return lines.join('\n');
}

function renderLoginHelper(login) {
  if (!login?.username) {
    return `
async function gotoWithOptionalLogin(page, path) {
  await page.goto(BASE_URL + path);
}
`;
  }

  const usernameSelector = login.usernameSelector ?? '';
  const passwordSelector = login.passwordSelector ?? '';
  const submitSelector = login.submitSelector ?? '';
  const loginUrl = login.loginUrl ?? '';

  return `
const LOGIN_URL = ${JSON.stringify(loginUrl)};
const LOGIN_USER = process.env.GOLDEN_MASTER_LOGIN_USER ?? '';
const LOGIN_PASS = process.env.GOLDEN_MASTER_LOGIN_PASS ?? '';
const LOGIN_USER_SELECTOR = process.env.GOLDEN_MASTER_LOGIN_USER_SELECTOR ?? ${JSON.stringify(usernameSelector)};
const LOGIN_PASS_SELECTOR = process.env.GOLDEN_MASTER_LOGIN_PASS_SELECTOR ?? ${JSON.stringify(passwordSelector)};
const LOGIN_SUBMIT_SELECTOR = process.env.GOLDEN_MASTER_LOGIN_SUBMIT_SELECTOR ?? ${JSON.stringify(submitSelector)};

async function gotoWithOptionalLogin(page, path) {
  const targetUrl = BASE_URL + path;
  await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
  await page.waitForLoadState('networkidle', { timeout: 5000 }).catch(() => {});
  const handled = await loginIfPresent(page);
  if (handled && stripHash(page.url()) !== stripHash(targetUrl)) {
    await page.goto(targetUrl, { waitUntil: 'domcontentloaded' }).catch(() => {});
    await page.waitForLoadState('networkidle', { timeout: 5000 }).catch(() => {});
  }
}

async function looksLikeLoginPage(page) {
  const currentUrl = page.url().toLowerCase();
  if (LOGIN_URL && stripHash(LOGIN_URL) === stripHash(page.url())) return true;
  if (/(login|signin|sign-in|auth)/.test(currentUrl)) return true;
  const passwordCount = await page.locator('input[type="password"]').count().catch(() => 0);
  return passwordCount > 0;
}

async function loginIfPresent(page) {
  const hasExplicitSelectors = Boolean(LOGIN_USER_SELECTOR || LOGIN_PASS_SELECTOR);
  if (!hasExplicitSelectors && !(await looksLikeLoginPage(page))) {
    return false;
  }

  const username = await resolveLoginLocator(page, LOGIN_USER_SELECTOR, [
    'input[autocomplete="username"]',
    'input[name*="user" i]',
    'input[name*="login" i]',
    'input[name*="mail" i]',
    'input[id*="user" i]',
    'input[id*="login" i]',
    'input[id*="mail" i]',
    'input[type="email"]',
    'input[type="text"]',
  ]);
  const password = await resolveLoginLocator(page, LOGIN_PASS_SELECTOR, [
    'input[autocomplete="current-password"]',
    'input[type="password"]',
  ]);

  if (!username && !password) return false;
  if (!LOGIN_USER || !LOGIN_PASS) {
    throw new Error('Login screen appeared. Set GOLDEN_MASTER_LOGIN_USER / GOLDEN_MASTER_LOGIN_PASS.');
  }

  let currentUsername = username;
  let currentPassword = password;

  if (currentUsername && !currentPassword) {
    await currentUsername.fill(LOGIN_USER);
    await submitLoginStep(page, currentUsername);
    await page.waitForLoadState('networkidle').catch(() => {});
    currentUsername = await resolveLoginLocator(page, LOGIN_USER_SELECTOR, [
      'input[autocomplete="username"]',
      'input[name*="user" i]',
      'input[name*="login" i]',
      'input[name*="mail" i]',
      'input[id*="user" i]',
      'input[id*="login" i]',
      'input[id*="mail" i]',
      'input[type="email"]',
      'input[type="text"]',
    ]);
    currentPassword = await resolveLoginLocator(page, LOGIN_PASS_SELECTOR, [
      'input[autocomplete="current-password"]',
      'input[type="password"]',
    ]);
  }

  if (!currentUsername && !currentPassword) return true;
  if (!currentPassword) {
    throw new Error('Could not locate the password field. Set GOLDEN_MASTER_LOGIN_PASS_SELECTOR.');
  }

  if (currentUsername) {
    await currentUsername.fill(LOGIN_USER);
  }
  await currentPassword.fill(LOGIN_PASS);
  await submitLoginStep(page, currentPassword);
  await page.waitForLoadState('networkidle').catch(() => {});
  return true;
}

async function resolveLoginLocator(page, explicitSelector, candidates) {
  const selectors = explicitSelector ? expandExplicitSelector(explicitSelector) : candidates;
  for (const selector of selectors) {
    const locator = page.locator(selector);
    const count = await locator.count().catch(() => 0);
    for (let i = 0; i < count; i++) {
      const candidate = locator.nth(i);
      if (await candidate.isVisible().catch(() => false)) return candidate;
    }
  }
  return undefined;
}

function expandExplicitSelector(selector) {
  const trimmed = (selector || '').trim();
  if (!trimmed) return [];
  if (/[#.[\\]: >+~,'"*=()]/.test(trimmed)) return [trimmed];
  const escaped = trimmed.replace(/["\\\\]/g, '\\\\$&');
  return [
    trimmed,
    '#' + trimmed,
    '[name="' + escaped + '"]',
    'input[name="' + escaped + '"]',
    'input[id="' + escaped + '"]',
  ];
}

async function submitLoginStep(page, fallbackField) {
  const submit = await resolveLoginLocator(page, LOGIN_SUBMIT_SELECTOR, [
    'button[type="submit"]',
    'input[type="submit"]',
    'button:has-text("ログイン")',
    'button:has-text("Login")',
    'button:has-text("Sign in")',
    'input[value*="ログイン"]',
    'input[value*="Login" i]',
  ]);
  if (submit) {
    await submit.click();
    return;
  }
  await fallbackField.press('Enter');
}

function stripHash(url) {
  try {
    const parsed = new URL(url);
    parsed.hash = '';
    return parsed.toString();
  } catch {
    return url;
  }
}
`;
}

function renderFormReadyHelper() {
  return `
async function ensureFormReadyForAssignments(page, selectors, submitSelector) {
  if (await isAuthorizationRequiredPage(page)) {
    throw new Error('Basic auth was not passed. Check GOLDEN_MASTER_BASIC_USER/PASS or GM_BASIC_USER/PASS.');
  }
  if (!Array.isArray(selectors) || selectors.length === 0) return;
  if (await hasAnyReachableSelector(page, selectors)) return;

  await advancePreconditionStep(page, submitSelector || '');
  if (await waitForAnyReachableSelector(page, selectors, 6000)) return;

  await advancePreconditionStep(page, '');
  if (await waitForAnyReachableSelector(page, selectors, 6000)) return;

  throw new Error('Failed to prepare the form: target input DOM not found (possibly stuck on a consent/transition gate).');
}

async function hasAnyReachableSelector(page, selectors) {
  const sample = selectors.slice(0, 6);
  for (const sel of sample) {
    const loc = page.locator(sel).first();
    const ok = await loc.isVisible().catch(async () => (await loc.count().catch(() => 0)) > 0);
    if (ok) return true;
  }
  return false;
}

async function waitForAnyReachableSelector(page, selectors, timeoutMs) {
  const started = Date.now();
  while (Date.now() - started < timeoutMs) {
    if (await hasAnyReachableSelector(page, selectors)) return true;
    await page.waitForTimeout(250).catch(() => {});
  }
  return false;
}

async function isAuthorizationRequiredPage(page) {
  const title = (await page.title().catch(() => '')).toLowerCase();
  const body = ((await page.locator('body').innerText().catch(() => '')) || '').toLowerCase();
  return title.includes('authorization required') || body.includes('authorization required');
}

async function advancePreconditionStep(page, submitSelector) {
  const checks = page.locator('input[type="checkbox"]');
  const n = await checks.count().catch(() => 0);
  const shouldAutoCheckSingle = n === 1;
  for (let i = 0; i < Math.min(n, 8); i++) {
    const cb = checks.nth(i);
    const text = await cb.evaluate((node) => {
      const id = node.id || '';
      const root = node.ownerDocument || document;
      const label = id ? root.querySelector('label[for="' + id.replace(/(["\\\\])/g, '\\\\$1') + '"]') : null;
      return ((node.name || '') + ' ' + id + ' ' + ((label && label.textContent) || '')).trim();
    }).catch(() => '');
    if (!shouldAutoCheckSingle && !/(agree|consent|同意|規約)/i.test(text)) continue;
    const checked = await cb.isChecked().catch(() => false);
    if (!checked) await cb.check({ force: true }).catch(() => {});
  }

  const clickCandidates = [
    submitSelector,
    'button:has-text("次へ")',
    'button:has-text("進む")',
    'button:has-text("同意")',
    'input[type="submit"]',
    'button[type="submit"]',
    '#btn0',
  ].filter(Boolean);

  for (const sel of clickCandidates) {
    const target = page.locator(sel).first();
    if (!(await target.count().catch(() => 0))) continue;
    const visible = await target.isVisible().catch(() => false);
    if (!visible) continue;
    const enabled = await target.isEnabled().catch(() => true);
    if (!enabled) continue;
    await target.click({ force: true, timeout: 3000 }).catch(() => {});
    await page.waitForTimeout(200).catch(() => {});
    await page.waitForLoadState('domcontentloaded', { timeout: 3000 }).catch(() => {});
    await page.waitForLoadState('networkidle', { timeout: 5000 }).catch(() => {});
    break;
  }
}

async function runPreSteps(page, preSteps) {
  for (const step of preSteps) {
    try {
      // Each step may depend on DOM the previous step just revealed; wait for it
      // to exist rather than assuming a fixed delay was long enough.
      await page.locator(step.selector).first().waitFor({ state: 'attached', timeout: 8000 });

      if (step.action === 'radio') {
        await selectRadioValue(page, step.selector, step.value);
      } else if (step.action === 'check') {
        await page.locator(step.selector).first().check({ force: true, timeout: 5000 });
      } else if (step.action === 'uncheck') {
        await page.locator(step.selector).first().uncheck({ force: true, timeout: 5000 });
      } else if (step.action === 'click') {
        await page.locator(step.selector).first().click({ force: true, timeout: 5000 });
      } else if (step.action === 'setFile') {
        await page.locator(step.selector).first().setInputFiles(step.path, { timeout: 8000 });
      }
      await page.waitForTimeout(200).catch(() => {});
      await page.waitForLoadState('domcontentloaded', { timeout: 3000 }).catch(() => {});
    } catch {
      // best-effort: an unavailable pre-step selector still lets the rest of the case run
    }
  }
}

async function selectRadioValue(page, selector, value) {
  const loc = page.locator(selector).first();
  if (!(await loc.count().catch(() => 0))) return;
  const selected = await loc.evaluate((node, targetValue) => {
    const input = node;
    const root = input.form || document;
    if (input.name) {
      const escapedName = (globalThis.CSS && CSS.escape)
        ? CSS.escape(input.name)
        : input.name.replace(/["\\\\]/g, '\\\\$&');
      const radios = Array.from(root.querySelectorAll('input[type="radio"][name="' + escapedName + '"]'));
      const target = radios.find((r) => r.value === targetValue);
      if (target) {
        target.click();
        return !!target.checked;
      }
    }
    if (input.value === targetValue) {
      input.click();
      return !!input.checked;
    }
    return false;
  }, value).catch(() => false);
  if (selected) return;
  await loc.check({ force: true }).catch(() => {});
}

async function clearRadioGroupSelection(page, selector) {
  const loc = page.locator(selector).first();
  if (!(await loc.count().catch(() => 0))) return;
  await loc.evaluate((node) => {
    const input = node;
    const root = input.form || document;
    if (input.name) {
      const escapedName = (globalThis.CSS && CSS.escape)
        ? CSS.escape(input.name)
        : input.name.replace(/["\\\\]/g, '\\\\$&');
      const radios = Array.from(root.querySelectorAll('input[type="radio"][name="' + escapedName + '"]'));
      for (const r of radios) r.checked = false;
      return;
    }
    input.checked = false;
  }).catch(() => {});
}
`;
}

function originOf(url) {
  try {
    return new URL(url).origin;
  } catch {
    return 'http://localhost';
  }
}

function pathOf(url) {
  try {
    const u = new URL(url);
    return u.pathname + u.search;
  } catch {
    return '/';
  }
}

function slugifyPath(p) {
  const s = p.replace(/^\/+/, '').replace(/[^a-zA-Z0-9_-]+/g, '-').replace(/^-+|-+$/g, '');
  return s || 'root';
}

module.exports = { generatePlaywrightCode };
