'use strict';
const fs = require('fs'); const path = require('path'); const { spawn } = require('child_process'); const { sessionDirFor } = require('../lib/sessionPaths'); const { parseListReporterLines, writeReplayReport } = require('../../core/report/replayReport'); const { readSiteConfig } = require('../../core/siteConfig'); const { ZapClient, mapCasesToAlerts } = require('../../core/security/zapClient');
function startReplay({ siteId, sessionId, options, onLog = () => {} }) {
  const dir = sessionDirFor(siteId, sessionId); if (options.useZap && !fs.readFileSync(path.join(dir, 'generated.spec.ts'), 'utf8').includes('WEB_SECURITY_PROXY_URL')) throw new Error('このセッションは旧形式です。「テストケースを編集」から保存して Playwright spec を再生成してから、ZAP 統合を実行してください。');
  const args = ['--prefix', path.join(__dirname, '..', '..'), 'playwright', 'test', './generated.spec.ts']; if (options.recordBaseline) args.push('--update-snapshots'); const env = { ...process.env, ...(options.baseUrl ? { BASE_URL: options.baseUrl } : {}), ...(options.useZap ? { WEB_SECURITY_PROXY_URL: options.zapProxyUrl } : {}) }; const child = spawn('npx', args, { cwd: dir, shell: false, env }); const lines = []; let cancelled = false;
  onLog(`[replay] session=${dir}`); onLog(`[replay] running: npx ${args.join(' ')}`);
  const completed = new Promise((resolve, reject) => { child.stdout.on('data', (chunk) => { const output = chunk.toString('utf8').split(/\r?\n/).filter(Boolean); lines.push(...output); if (!cancelled) output.forEach(onLog); }); child.stderr.on('data', (chunk) => { if (!cancelled) chunk.toString('utf8').split(/\r?\n/).filter(Boolean).forEach(onLog); }); child.on('error', reject); child.on('close', async (exitCode) => { if (cancelled) return; try { const results = parseListReporterLines(lines); const zap = options.useZap ? await collectZapArtifacts({ siteId, sessionId, dir, options, onLog }) : undefined; let reportUrl, markdownUrl; if (results.length) { writeReplayReport(dir, { results, exitCode, baseUrl: options.baseUrl }); reportUrl = `/api/sites/${siteId}/sessions/${sessionId}/replay-report.html`; markdownUrl = `/api/sites/${siteId}/sessions/${sessionId}/replay-report.md`; } resolve({ exitCode, ok: exitCode === 0, reportUrl, markdownUrl, zap }); } catch (error) { reject(error); } }); });
  return { completed, cancel() { cancelled = true; child.kill(); } };
}
async function collectZapArtifacts({ siteId, sessionId, dir, options, onLog }) { try { const zap = new ZapClient({ baseUrl: options.zapBaseUrl }); const target = options.baseUrl || readSiteConfig(siteId).baseUrl; onLog(`ZAP 接続: ${(await zap.version()).version}`); let result; if (options.activeZap) { if (!options.authorized) throw new Error('ZAP アクティブ検査には診断許可の確認が必要です'); const scanId = await zap.startActiveScan(target); result = { scanId, ...await zap.waitForScan(scanId, { onProgress: onLog }) }; } const alerts = mapCasesToAlerts(await zap.alerts(target), await zap.messages(target)); fs.writeFileSync(path.join(dir, 'zap-alerts.json'), JSON.stringify({ target, scannedAt: new Date().toISOString(), alerts }, null, 2)); return { ...result, alerts: alerts.length, alertsUrl: `/api/sites/${siteId}/sessions/${sessionId}/zap-alerts.json` }; } catch (error) { onLog(`ZAP: ${error.message}`); return { error: error.message }; } }
module.exports = { startReplay };
